### ISSUE TITLE
11-Referencias

### ISSUE THREAD

**Issue by sensatte** [sensatte/TFG-Smart-Mirror#31]

**Comment by sensatte** [comment]
Web de kivy

**Comment by sensatte** [comment]
flaticon

**Comment by sensatte** [comment]
stackoverflow

**Comment by Carcotmed** [comment]
OpenWeather API https://openweathermap.org/guide

**Comment by sensatte** [comment]
https://es.wikipedia.org/wiki/Microcomputadora

**Comment by sensatte** [comment]
https://forum.freecodecamp.org/t/free-api-inspirational-quotes-json-with-code-examples/311373/1
